routes/web.php
<?php

use Illuminate\Support\Facades\Route;


Route::group(['name' => 'Building Blocks', 'groupName' => 'Building Blocks','prefix'=>'building-blocks'], function () {
    //blocks related routes
    Route::get('overfolders/grid', 'PackageControllers\OverFolderCrudController@grid')->name('overfolders.grid');
    Route::resource('overfolders', 'PackageControllers\OverFolderCrudController');

    Route::get('folders/grid', 'PackageControllers\FolderCrudController@grid')->name('folders.grid');
    Route::resource('folders', 'PackageControllers\FolderCrudController');

    Route::get('blocks/grid', 'PackageControllers\BlockCrudController@grid')->name('blocks.grid');
    Route::resource('blocks', 'PackageControllers\BlockCrudController');
});

resources/views/Blocks/add.blade.php
@extends('Admin.layout')
@section('styles')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet" />
@endsection
@section('content')
    @include('Admin.partials.form-alert')
    @include('Admin.partials.breadcumbs', ['header' => __('buildingblocks.Blocks')])
    <div class="content-body">
        @if (isset($model))
            <form action="{{ route('admin.blocks.update', ['block' => $model->id]) }}" method="POST" class="form-horizontal"
                enctype="multipart/form-data">
            @else
                <form action="{{ route('admin.blocks.store') }}" method="POST" class="form-horizontal"
                    enctype="multipart/form-data">
        @endif

        <div class="row">
            <div class="col-md-12">
                <div class="card">

                    <div class="card-header">
                        @if (isset($model))
                            <h4 class="card-title" id="basic-layout-form-center">{{ __('general.Update') }}
                                ({{ request()->get('translating_lang', app()->getLocale()) }})</h4>
                        @else
                            <h4 class="card-title" id="basic-layout-form-center">{{ __('general.Create new') }}</h4>
                        @endif
                    </div>

                    <div class="card-body">
                        <div class="row">
                            <div class="col-md-6 col-sm-12 border-right-blue-grey border-right-lighten-5">

                                {{ csrf_field() }}

                                @if (isset($model))
                                    <input type="hidden" name="_method" value="PATCH">

                                    <input type="hidden" name="id" id="id" class="form-control"
                                        readonly="readonly" value="{{ $model->id }}">
                                @else
                                    <input type="hidden" name="id" id="id" class="form-control"
                                        readonly="readonly" value="">
                                @endif
                                <h4 class="form-section"><i class="fa fa-tags"></i>{{ __('buildingblocks.Folder content') }}
                                </h4>
                                <div class="form-group">
                                    <label for="name"
                                        class="col-sm-12 control-label">{{ __('buildingblocks.name') }}</label>
                                    <div class="col-sm-12">
                                        <input required type="text" name="name" id="name" class="form-control"
                                            value="{{ isset($model) ? $model->name : old('name') ?? '' }}">
                                    </div>
                                </div>


                                <div class="form-group">
                                    <label for="short_description"
                                        class="col-sm-12 control-label">{{ __('posts.short_description') }}</label>
                                    <div class="col-sm-12">
                                        <textarea rows="5" required name="short_description" id="short_description" class="form-control">{{ isset($model) ? $model->short_description : old('short_description') ?? '' }}</textarea>
                                    </div>
                                </div>

                                <div class="form-group">
                                    <label for="main_description"
                                        class="col-sm-12 control-label">{{ __('posts.main_description') }}</label>
                                    <div class="col-sm-12">
                                        <textarea required name="main_description" id="main_description" class="form-control summernote-body">{{ isset($model) ? $model->main_description : old('main_description') ?? '' }}</textarea>
                                    </div>
                                </div>


                                <div class="form-group">
                                    <label for="additional_description"
                                        class="col-sm-12 control-label">{{ __('posts.additional_description') }}</label>
                                    <div class="col-sm-12">
                                        <textarea name="additional_description" id="additional_description" class="form-control summernote-body">{{ isset($model) ? $model->additional_description : old('additional_description') ?? '' }}</textarea>
                                    </div>
                                </div>



                                @component('Admin.components.form-actions', ['model' => isset($model) ? $model : null])
                                @endcomponent
                            </div>
                            <div class="col-md-6 col-sm-12 border-right-blue-grey border-right-lighten-5">
                                <h4 class="form-section"><i class="fa fa-tags"></i>{{ __('buildingblocks.More Information') }}
                                </h4>
                                @component('Admin.BuildingBlocks.Folders.components.folder-selector',
                                ['model' => isset($model) ? $model : null, 'filedName' => 'folder_id', 'folders' => $folders])
                                @endcomponent

                                {{-- @component('Admin.components.single-image-type', ['model' => isset($model) ? $model : null, 'filedName' => 'image_url'])
                                @endcomponent --}}
                                @component('Admin.components.single-image-picker',
                                    ['model' => isset($model) ? $model : null, 'filedName' => 'single_attachment'])
                                @endcomponent

                                @component('Admin.components.multiple-images', ['model' => isset($model) ? $model : null])
                                @endcomponent

                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
    </form>
    </div>
@endsection
@section('scripts')
    {{-- @push('component-scripts')
<script></script>
@endpush --}}
@endsection

resources/views/Blocks/index.blade.php
@extends('Admin.layout')

@section('content')

@include('Admin.partials.form-alert')
@include('Admin.partials.breadcumbs',['header'=>__('buildingblocks.Blocks')])

<div class="content-body">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-content show">
                    <div class="card-body">
                        @component('Admin.BuildingBlocks.Blocks.components.table', ['foo' => 'bar'])
                        @endcomponent
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection


@section('scripts')

    <link rel="stylesheet" type="text/css" href="{{ asset("vendors/css/tables/datatable/datatables.min.css")}}">
    <script src="{{ asset("vendors/js/tables/datatable/datatables.min.js")}}"  type="text/javascript"></script>
    <script type="text/javascript">

        let params = (new URL(document.location)).searchParams;
        let filtered_folder = params.get("folder");
        let queryParam = "";

        if(filtered_folder != null && filtered_folder != ""){
            queryParam =  "?where[0]=folder_id&where[1]==&where[2]="+filtered_folder;
        }



        var theGrid = null;
        var editRoute = "{{route('admin.blocks.edit',['block'=>'sampleId'])}}";
        var deleteRoute = "{{route('admin.blocks.destroy',['block'=>'sampleId'])}}";
        var gridRoute = "{{route('admin.blocks.grid')}}"+ queryParam;

        $(document).ready(function(){
            theGrid = $('#thegrid').DataTable({"bStateSave": true,
                "language": {
                    "url":"{{ asset(__('general.dataTable'))}}"
                },
                "processing": true,
                "serverSide": true,
                "paging": true,
                "pageLength": 10,
                "ordering": true,
                "responsive": false,
                "ajax": gridRoute,
                "columnDefs": [
                    {
                        "render": function ( data, type, row ) {
                            return '<a >'+data+'</a>';
                        },"className":"action-col","orderable": false,
                        "targets": 0,
                        "visible": false,

                    },

                    // {
                    //     "render": function ( data, type, row ) {
                    //         return '<button href="'+editRoute.replace('sampleId',row[0])+'" class="btn btn-info btn-sm">{{__('Update')}}</button>';
                    //     },"className":"action-col","orderable": false,
                    //     "targets": 6
                    // },
                    // {
                    //     "render": function ( data, type, row ) {
                    //         return '<a href="#" onclick="return doDelete('+row[0]+')" class="btn btn-danger btn-sm">{{__('Delete')}}</a>';
                    //     },"className":"action-col","orderable": false,
                    //     "targets": 7
                    // },
                ]
            });
        });

        $(document).on('click','.deleteTranslation',function (e) {
            e.preventDefault();
            var id = $(this).data('id');
            var lang = $(this).data('lang');
            @if(\Illuminate\Support\Facades\Auth::user()->isSuperAdmin())
            doDelete(id,lang);
            @endif
        })


        function doDelete(id,lang) {
            // if(confirm('You really want to delete this record?')) {
                var lang = lang ? lang: '';
            swal({
                title: "{{__('general.Warning!')}}",
                text: "{{__('general.Are you sure you need to delete this item? this change cannot be undone.')}}",
                icon: "warning",
                buttons: {
                    cancel: {
                        text: "{{__('general.Cancel')}}",
                        value: null,
                        visible: !0,
                        className: "",
                        closeModal: !1
                    },
                    confirm: {
                        text: "{{__('general.Yes.Delete')}}",
                        value: !0,
                        visible: !0,
                        className: "",
                        closeModal: !1
                    }
                }
            }).then(e => {
                if (e) {
                    $.ajax({
                        dataType: 'json',
                        method: 'delete',
                        url: deleteRoute.replace('sampleId',id)+'?delete_lang='+lang,
                    }).done(function (response) {
                        swal("{{__('general.Success!')}}", "{{__('general.Item deleted!!')}}", "success").then(() => {
                            theGrid.ajax.reload();
                        });
                    }).fail(function (erroErrorr) {
                        swal("{{__('general.Error')}}", "{{__('general.Error Occured')}}", "error");
                    });
                } else {
                    swal("{{__('general.Cancelled')}}", "{{__("general.It's safe")}}", "error");
                }
            });

            return false;
        }
    </script>
    <script src="{{ asset("vendors/js/extensions/sweetalert.min.js") }}" type="text/javascript"></script>

    @yield('component-scripts')
@endsection

resources/views/Blocks/show.blade.php
@extends('Admin.layout')


@section('content')

@endsection