routes/web.php
<?php

use Illuminate\Support\Facades\Route;


Route::group(['name' => 'Building Blocks', 'groupName' => 'Building Blocks','prefix'=>'building-blocks'], function () {
    //blocks related routes
    Route::get('overfolders/grid', 'PackageControllers\OverFolderCrudController@grid')->name('overfolders.grid');
    Route::resource('overfolders', 'PackageControllers\OverFolderCrudController');

    Route::get('folders/grid', 'PackageControllers\FolderCrudController@grid')->name('folders.grid');
    Route::resource('folders', 'PackageControllers\FolderCrudController');

    Route::get('blocks/grid', 'PackageControllers\BlockCrudController@grid')->name('blocks.grid');
    Route::resource('blocks', 'PackageControllers\BlockCrudController');
});

resources/views/Folders/add.blade.php
@extends('Admin.layout')
@section('styles')
    <link href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.7/css/select2.min.css" rel="stylesheet"/>
@endsection
@section('content')
@include('Admin.partials.form-alert')
@include('Admin.partials.breadcumbs',['header'=>__('buildingblocks.Folders')])
<div class="content-body">
    @if(isset($model))
    <form action="{{ route('admin.folders.update',['folder'=>$model->id]) }}" method="POST"
          class="form-horizontal" enctype="multipart/form-data">
        @else
            <form action="{{route('admin.folders.store')}}" method="POST"
                  class="form-horizontal" enctype="multipart/form-data">
        @endif

    <div class="row">
        <div class="col-md-12">
            <div class="card">

                <div class="card-header">
                    @if (isset($model))
                        <h4 class="card-title" id="basic-layout-form-center">{{__('general.Update')}} ({{request()->get('translating_lang', app()->getLocale())}})</h4>
                    @else
                        <h4 class="card-title" id="basic-layout-form-center">{{__('general.Create new')}}</h4>
                    @endif
                </div>

                    <div class="card-body">
                        <div class="row">
                        <div class="col-md-8 col-sm-12 border-right-blue-grey border-right-lighten-5">


                            {{ csrf_field() }}

                            @if (isset($model))

                                <input type="hidden" name="_method" value="PATCH">

                                        <input type="hidden" name="id" id="id" class="form-control" readonly="readonly" value="{{$model->id}}">
                                @else
                                        <input type="hidden" name="id" id="id" class="form-control" readonly="readonly" value="">
                            @endif
                            <h4 class="form-section"><i class="fa fa-tags"></i>{{ __("buildingblocks.Folder content") }}</h4>
                            <div class="form-group">
                                <label for="name" class="col-sm-12 control-label required">{{__('buildingblocks.name')}}</label>
                                <div class="col-sm-12">
                                    <input required type="text" name="name" id="name" class="form-control" value="{{isset($model) ? $model->name : (old('name'))?? '' }}">
                                </div>
                            </div>

                                @component('Admin.BuildingBlocks.OverFolders.components.overfolder-selector',['model'=>isset($model) ? $model : null,'filedName'=>"over_folder_id",'overfolders'=>$overfolders])
                                @endcomponent


                                @component('Admin.components.form-actions',['model'=>isset($model) ? $model : null])
                                @endcomponent
                            </div>

                          </div>
                    </div>
                </div>
            </div>
        </div>
    </div>
</form>
</div>


@endsection
@section('scripts')

{{-- @stack('component-scripts') --}}
@endsection

resources/views/Folders/index.blade.php
@extends('Admin.layout')

@section('content')

@include('Admin.partials.form-alert')
@include('Admin.partials.breadcumbs',['header'=>__('buildingblocks.Folders')])

<div class="content-body">
    <div class="row">
        <div class="col-md-12">
            <div class="card">
                <div class="card-content show">
                    <div class="card-body">
                        @component('Admin.BuildingBlocks.Folders.components.table', ['foo' => 'bar'])
                        @endcomponent
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>

@endsection


@section('scripts')

    <link rel="stylesheet" type="text/css" href="{{ asset("vendors/css/tables/datatable/datatables.min.css")}}">
    <script src="{{ asset("vendors/js/tables/datatable/datatables.min.js")}}"  type="text/javascript"></script>
    <script type="text/javascript">

        let params = (new URL(document.location)).searchParams;
        let filtered_overfolder = params.get("overfolder");

        let queryParam = "";

        if(filtered_overfolder != null && filtered_overfolder != ""){
            queryParam =  "?where[0]=over_folder_id&where[1]==&where[2]="+filtered_overfolder;
        }


        var theGrid = null;
        var editRoute = "{{route('admin.folders.edit',['folder'=>'sampleId'])}}";
        var deleteRoute = "{{route('admin.folders.destroy',['folder'=>'sampleId'])}}";
        var gridRoute = "{{route('admin.folders.grid')}}" + queryParam ;

        $(document).ready(function(){
            theGrid = $('#thegrid').DataTable({"bStateSave": true,
                "language": {
                    "url":"{{ asset(__('general.dataTable'))}}"
                },
                "processing": true,
                "serverSide": true,
                "paging": true,
                "pageLength": 10,
                "ordering": true,
                "responsive": false,
                "ajax": gridRoute,
                "columnDefs": [
                    {
                        "render": function ( data, type, row ) {
                            return '<a >'+data+'</a>';
                        },"className":"action-col","orderable": false,
                        "targets": 0,
                        "visible": false,

                    },

                    // {
                    //     "render": function ( data, type, row ) {
                    //         return '<button href="'+editRoute.replace('sampleId',row[0])+'" class="btn btn-info btn-sm">{{__('Update')}}</button>';
                    //     },"className":"action-col","orderable": false,
                    //     "targets": 6
                    // },
                    // {
                    //     "render": function ( data, type, row ) {
                    //         return '<a href="#" onclick="return doDelete('+row[0]+')" class="btn btn-danger btn-sm">{{__('Delete')}}</a>';
                    //     },"className":"action-col","orderable": false,
                    //     "targets": 7
                    // },
                ]
            });
        });

        $(document).on('click','.deleteTranslation',function (e) {
            e.preventDefault();
            var id = $(this).data('id');
            var lang = $(this).data('lang');
            @if(\Illuminate\Support\Facades\Auth::user()->isSuperAdmin())
            doDelete(id,lang);
            @endif
        })


        function doDelete(id,lang) {
            // if(confirm('You really want to delete this record?')) {
                var lang = lang ? lang: '';
            swal({
                title: "{{__('general.Warning!')}}",
                text: "{{__('general.Are you sure you need to delete this item? this change cannot be undone.')}}",
                icon: "warning",
                buttons: {
                    cancel: {
                        text: "{{__('general.Cancel')}}",
                        value: null,
                        visible: !0,
                        className: "",
                        closeModal: !1
                    },
                    confirm: {
                        text: "{{__('general.Yes.Delete')}}",
                        value: !0,
                        visible: !0,
                        className: "",
                        closeModal: !1
                    }
                }
            }).then(e => {
                if (e) {
                    $.ajax({
                        dataType: 'json',
                        method: 'delete',
                        url: deleteRoute.replace('sampleId',id)+'?delete_lang='+lang,
                    }).done(function (response) {
                        swal("{{__('general.Success!')}}", "{{__('general.Item deleted!!')}}", "success").then(() => {
                            theGrid.ajax.reload();
                        });
                    }).fail(function (erroErrorr) {
                        swal("{{__('general.Error')}}", "{{__('general.Error Occured')}}", "error");
                    });
                } else {
                    swal("{{__('general.Cancelled')}}", "{{__("general.It's safe")}}", "error");
                }
            });

            return false;
        }
    </script>
    <script src="{{ asset("vendors/js/extensions/sweetalert.min.js") }}" type="text/javascript"></script>

    @yield('component-scripts')
@endsection

resources/views/Folders/show.blade.php
@extends('Admin.layout')


@section('content')

@endsection