routes/web.php
<?php

use Illuminate\Support\Facades\Route;


Route::group(['name' => 'Building Blocks', 'groupName' => 'Building Blocks','prefix'=>'building-blocks'], function () {
    //blocks related routes
    Route::get('overfolders/grid', 'PackageControllers\OverFolderCrudController@grid')->name('overfolders.grid');
    Route::resource('overfolders', 'PackageControllers\OverFolderCrudController');

    Route::get('folders/grid', 'PackageControllers\FolderCrudController@grid')->name('folders.grid');
    Route::resource('folders', 'PackageControllers\FolderCrudController');

    Route::get('blocks/grid', 'PackageControllers\BlockCrudController@grid')->name('blocks.grid');
    Route::resource('blocks', 'PackageControllers\BlockCrudController');
});

resources/views/Blocks/components/table.blade.php
<div class="row">
    <div class="col-md-12 col-12 mb-2">
        <div class="mb-2 pull-left">
            @component("Admin.components.language-picker")
           @endcomponent
        </div>
        <div class="mb-2 pull-right">
            <a href="{{route('admin.blocks.create')}}" class="btn btn-secondary btn-block-sm"><i class="ft-file-plus"></i> {{__('general.Create new')}}</a>

            <a href="{{ route('admin.folders.index') }}">
                <button type="button" href="" class="btn btn-warning mr-1">
                    <i class="ft-arrow-left"></i> {{__('trainings.general.goBack')}}
                </button></a>
        </div>
    </div>
</div>

<div class="table-responsive">
    <table class="table table-bordered table-striped full-width" id="thegrid">
        <thead>
        <tr>
            <th>{{__('buildingblocks.id')}}</th>
            <th>{{__('buildingblocks.name')}}</th>
            <th>{{__('buildingblocks.folder')}}</th>
            <th class="action-col">{{__('general.Translate')}}</th>
            <th class="action-col" >{{__('general.Update')}}</th>
            <th class="action-col" >{{__('general.Delete')}}</th>
        </tr>
        </thead>
        <tbody>
        </tbody>
    </table>
</div>